### ISSUE TITLE
Working with standalone home-manager with flakes

### ISSUE THREAD

**Issue by arilebedey** [pierrot-lc/nvim-nix#3]
I'm unable to properly make nix-kickstart.nvim work with h-m (home-manager) and I've noticed that you have a fork of the project running on h-m, so I'm asking for some help, since it could be a trivial issue to resolve for you.

I tried my best. I added this to `.config/home-manager/flake.nix`:
```nix
    nvim-nix = {
      url = "github:nix-community/kickstart-nix.nvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```
I added nvim-nix to the outputs of this flake, and tried adding the overlays like so:
```nix
  outputs = { nixpkgs, home-manager, nvim-nix, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};

    in {
      homeConfigurations."ari" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [ ./home.nix ];
        # OVERLAYS
        nixpkgs.overlays = [
          nvim-nix.overlays.default
        ];
```
Then I added this to `home.nix`:
```nix
home.packages = with pkgs; [
    nvim-pkg
];
```
Now when running `home-manager switch --flake /home/ari/.config/home-manager/` after `nix flake lock`, h-m seems to complain about nixpkgs.overlays definition:
```
error:
       … from call site

         at /nix/store/w4gdyp45vlg72k9zn9pwcis50sggfv09-source/flake.nix:25:34:

           24|     in {
           25|       homeConfigurations."ari" = home-manager.lib.homeManagerConfiguration {
             |                                  ^
           26|         inherit pkgs;

       error: function 'homeManagerConfiguration' called with unexpected argument 'nixpkgs'

       at /nix/store/4pkq7jkg67g1y4252kp7ckqfbygri8bh-source/flake.nix:41:36:

           40|         hm = (import ./modules/lib/stdlib-extended.nix nixpkgs.lib).hm;
           41|         homeManagerConfiguration = { modules ? [ ], pkgs, lib ? pkgs.lib
             |                                    ^
           42|           , extraSpecialArgs ? { }, check ? true
```
I'm probably doing something wrong with the overlays. Here is my full h-m/flake.nix just in case:
```nix
{
  description = "Home Manager configuration of ari";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nvim-nix = {
      url = "github:arilebedey/nix-community/kickstart-nix.nvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { nixpkgs, home-manager, nvim-nix, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};

    in {
      homeConfigurations."ari" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [ ./home.nix ];

        nixpkgs.overlays = [
          nvim-nix.overlays.default
        ];
      };
    };
}
```

**Comment by arilebedey** [comment]
Since I want to call `pkgs.nvim.nix` from `home.nix` as described in the README.md of this repo, overlays should be modifying `      pkgs = nixpkgs.legacyPackages.${system};` in h-m/flake.nix but I do not understand how. This is probably the issue.

**Comment by pierrot-lc** [comment]
Hi,
First you need to know that my repository is my own adaptation of `kickstart-nix.nvim`, with some slights modifications (notably the added nix module). You seem to be talking about the original `kickstart-nix.nvim` project, and my answer will be about this project and not mine.

Indeed your issue is about the overlay. I'm still wrapping my head around all this nix world, but from my understanding, adding an overlay to `pkgs` is how you can add packages to the list of available packages listed in `pkgs`. Do to so, you should modify the way you declare your `pkgs` variable in your outputs by doing something like this:

```nix
{
  description = "Home Manager configuration of ari";

  inputs = {
    nixpkgs.url = "github:nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nvim-nix = {
      url = "github:arilebedey/kickstart-nix.nvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { nixpkgs, home-manager, nvim-nix, ... }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        overlays = [
          nvim-nix.overlays.default
      };
    in {
      homeConfigurations."ari" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [ ./home.nix ];
        ];
      };
    };
```

Then in your `home.nix`:
```nix
{pkgs, ...}:
{
home.packages = with pkgs; [
    nvim-pkg
];
}
```

Also, note that I have modified the github url of the  kickstart-nix.nvim flake input as this is how it should be written to point to your own implementation of the repo. You can replace it with:

```nix
  nvim-nix = {
      url = "github:nix-community/kickstart-nix.nvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

if you want to keep using the default implementation of the community.

**Comment by arilebedey** [comment]
Thank you.

Your assumptions were correct and I am now able to launch this flake from the repo we both templated from (as you noticed as well) through home-manager with flakes! 🥳

There are two corrections that you made that made it work:
1.  Changed the `pkgs` definition in `h-m/flake.nix` in the variable section (between `let` and `in`)

From:
```nix
      pkgs = nixpkgs.legacyPackages.${system};
```
To:
```nix
      pkgs = import nixpkgs {
        inherit system;
        overlays = [
          nvim-nix.overlays.default
      };
```
2. Called the right package name from within `home.nix` as `nvim-pkg`; which I believe comes from the overlay-defining file of the nix folder of the nix-kickstart.nvim project, and is also documented on the front page of the github repository.

I'm writing this for comparison and documentation sake, and might use this for further investigation of the topics mentioned and principles uncovered.

One thing that ticks me is that it appears that this change to the `pkgs` definition omits `legacyPackages.${system}`.

**Comment by pierrot-lc** [comment]
Glad I could help! I don't know exactly the use case of `legacyPackages`. I think it is deprecated but i'm not sure.
